{% set name = "pydiverse-transform" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydiverse_transform-{{ version }}.tar.gz
  sha256: 017151c342113fde3716a358be6e9a59bfaf9671c9983aba347420daf85fa434

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - pandas >=2.0.0
    - polars >=1.6.0
    - sqlalchemy >=2.0.0
    - pyarrow >=11.0.0
  run_constrained:
    - python-duckdb >=0.8.1
    - duckdb-engine >=0.9.1
    - psycopg2 >=2.9.3
    - pyodbc >=4.0.35

test:
  imports:
    - pydiverse.transform
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydiverse/pydiverse.transform
  summary: Pipe based dataframe manipulation library that can also transform data on SQL databases
  license: BSD-3-Clause
  license_file:
    - LICENSE
  dev_url: https://github.com/pydiverse/pydiverse.transform

extra:
  recipe-maintainers:
    - finn-rudolph
    - pavelzw
    - windiana42
    - NMAC427
