context:
  name: pydiverse-transform
  version: "0.5.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydiverse_transform-${{ version }}.tar.gz
  sha256: 4c088dbb9bbde10feb16896db109c7e01c995be0b3a20059fbceadddc12bbce4

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - pandas >=2.3.0,<3
    - pyarrow >=20.0.0,<21
    - polars >=1.30.0,<2
    - pydiverse-common >=0.3.4,<0.4
    - sqlalchemy >=2.0.41,<3
  run_constraints:
    - python-duckdb >=1.3.0,<2
    - duckdb-engine >=0.15.0,<0.16
    - psycopg2 >=2.9.3
    - pyodbc >=4.0.35

tests:
  - python:
      imports:
        - pydiverse.transform
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/pydiverse/pydiverse.transform
  documentation: https://pydiversetransform.readthedocs.io/
  summary: Pipe based dataframe manipulation library that can also transform data on SQL databases
  license: BSD-3-Clause
  license_file:
    - LICENSE
  repository: https://github.com/pydiverse/pydiverse.transform

extra:
  recipe-maintainers:
    - finn-rudolph
    - pavelzw
    - windiana42
    - NMAC427
